const state={dashboard:null,customers:[],services:[],rates:[],invoices:[],activeInvoice:null};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=c=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100);
const date=v=>v?new Intl.DateTimeFormat('es-ES').format(new Date(String(v).includes('T')?v:`${String(v).slice(0,10)}T12:00:00`)):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,options={}){const r=await fetch(url,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.issues?.join(' ')||data.error||`Error ${r.status}`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function empty(message){return `<div class="empty">${esc(message)}</div>`}
function statusClass(s){return s==='Enviada'?'sent':s==='Lista para revisión'?'review':s.includes('Error')?'error':''}
function invoiceTable(rows){if(!rows.length)return empty('Todavía no hay facturas.');return `<table><thead><tr><th>Número</th><th>Cliente</th><th>Periodo</th><th>Estado</th><th class="numeric">Total</th><th></th></tr></thead><tbody>${rows.map(i=>`<tr><td>${esc(i.invoice_number||'Sin emitir')}</td><td><strong>${esc(i.customer_name)}</strong></td><td>${date(i.period_start)} – ${date(i.period_end)}</td><td><span class="status ${statusClass(i.status)}">${esc(i.status)}</span></td><td class="numeric"><strong>${money(i.total_cents)}</strong></td><td class="numeric"><button class="text-button" data-invoice="${i.id}">Revisar →</button></td></tr>`).join('')}</tbody></table>`}
async function load(){const [dashboard,customers,services,rates,invoices]=await Promise.all(['/api/dashboard','/api/customers','/api/services','/api/rates','/api/invoices'].map(api));Object.assign(state,{dashboard,customers,services,rates,invoices});render()}
function render(){const d=state.dashboard;$('#sync-status').textContent=d.lastSync?`Actualizado ${date(d.lastSync)}`:'Sin sincronizar';$('#metrics').innerHTML=[['Clientes activos',d.customers,'Identidades importadas'],['Líneas',d.services,`${d.missingRates} sin tarifa propia`],['Listas para revisión',d.invoices.find(x=>x.status==='Lista para revisión')?.count||0,'Requieren confirmación'],['Enviadas',d.invoices.find(x=>x.status==='Enviada')?.count||0,'Con Gmail confirmado']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div><div class="metric-note">${x[2]}</div></div>`).join('');$('#recent-invoices').innerHTML=invoiceTable(state.invoices.slice(0,6));const alerts=[];if(!d.integrations.nexlink)alerts.push(['Nexlink sin configurar','Añade el token o las credenciales en Railway.']);if(!d.integrations.notion)alerts.push(['Notion sin configurar','Falta compartir la base con una integración.']);if(!d.integrations.gmail)alerts.push(['Gmail sin configurar','Falta la contraseña de aplicación.']);if(d.missingRates)alerts.push([`${d.missingRates} líneas sin tarifa`,'No podrán incluirse en una vista previa.']);if(!d.settings.invoice_series||!d.settings.next_invoice_number)alerts.push(['Numeración incompleta','Define serie y número inicial.']);$('#attention-list').innerHTML=alerts.length?alerts.map(a=>`<div class="attention-item"><strong>${esc(a[0])}</strong><span>${esc(a[1])}</span></div>`).join(''):'<div class="attention-item"><strong>Sin bloqueos detectados</strong><span>Los controles básicos están completos.</span></div>';$('#customers-table').innerHTML=customerTable();$('#services-table').innerHTML=serviceTable();$('#invoices-table').innerHTML=invoiceTable(state.invoices);renderSettings();bindDynamic()}
function customerTable(){if(!state.customers.length)return empty('Sin clientes. Ejecuta la sincronización con Nexlink.');return `<table><thead><tr><th>Cliente</th><th>NIF/CIF</th><th>Email</th><th>Líneas</th><th>Estado de datos</th><th></th></tr></thead><tbody>${state.customers.map(c=>{const ready=c.tax_id&&c.billing_address&&c.billing_email;return `<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.phone||'')}</small></td><td>${esc(c.tax_id||'Pendiente')}</td><td>${esc(c.billing_email||'Pendiente')}</td><td>${c.services}</td><td><span class="status ${ready?'sent':'error'}">${ready?'Completo':'Revisión necesaria'}</span></td><td><button class="text-button" data-edit-customer="${c.id}">Editar</button></td></tr>`}).join('')}</tbody></table>`}
function serviceTable(){if(!state.services.length)return empty('Sin líneas. Ejecuta la sincronización con Nexlink.');const options=state.rates.map(r=>`<option value="${r.id}">${esc(r.name)} · ${money(r.monthly_fee_cents)}</option>`).join('');return `<table><thead><tr><th>Línea</th><th>Cliente</th><th>Producto Nexlink</th><th>Tarifa facturable</th><th>Descuento €</th><th></th></tr></thead><tbody>${state.services.map(s=>`<tr><td><strong>${esc(s.line_identifier)}</strong><br><small>${esc(s.operator||'')}</small></td><td>${esc(s.customer_name)}</td><td>${esc(s.provider_product||'Sin identificar')}</td><td><select class="assign-select" data-service-rate="${s.id}"><option value="">Seleccionar tarifa…</option>${options}</select></td><td><input class="assign-select" data-service-discount="${s.id}" type="number" min="0" step="0.01" value="${Number(s.discount_cents||0)/100}"></td><td><button class="text-button" data-save-service="${s.id}">Guardar</button> · <button class="text-button" data-usage-service="${s.id}">Registrar GB</button></td></tr>`).join('')}</tbody></table>`}
function renderSettings(){const f=$('#settings-form'),s=state.dashboard.settings;f.invoiceSeries.value=s.invoice_series||'';f.nextInvoiceNumber.value=s.next_invoice_number||'';f.defaultVatRate.value=s.default_vat_rate==null?'':Number(s.default_vat_rate)*100;f.defaultPaymentDays.value=s.default_payment_days??'';$('#integrations').innerHTML=Object.entries(state.dashboard.integrations).map(([k,v])=>`<div class="integration ${v?'ok':''}"><i></i><span>${k[0].toUpperCase()+k.slice(1)} · ${v?'Configurado':'Pendiente'}</span></div>`).join('')}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
function bindDynamic(){$$('[data-invoice]').forEach(b=>b.onclick=()=>openPreview(b.dataset.invoice));$$('[data-service-rate]').forEach(s=>{s.value=state.services.find(x=>x.id===s.dataset.serviceRate)?.rate_id||''});$$('[data-save-service]').forEach(b=>b.onclick=async()=>{const id=b.dataset.saveService,rateId=$(`[data-service-rate="${id}"]`).value,discount=Number($(`[data-service-discount="${id}"]`).value||0);if(!rateId)return toast('Selecciona una tarifa');await api(`/api/services/${id}/rate`,{method:'PATCH',body:JSON.stringify({rateId,discountCents:Math.round(discount*100)})});toast('Condiciones de línea guardadas');await load()});$$('[data-usage-service]').forEach(b=>b.onclick=()=>{const service=state.services.find(s=>s.id===b.dataset.usageService),f=$('#usage-form');f.serviceId.value=service.id;$('#usage-line').textContent=`${service.line_identifier} · ${service.customer_name}`;$('#usage-dialog').showModal()});$$('[data-edit-customer]').forEach(b=>b.onclick=()=>{const c=state.customers.find(x=>x.id===b.dataset.editCustomer),f=$('#customer-form');f.customerId.value=c.id;f.taxId.value=c.tax_id||'';f.billingEmail.value=c.billing_email||'';f.billingAddress.value=c.billing_address||'';f.vatRate.value=c.vat_rate==null?'':Number(c.vat_rate)*100;f.paymentDays.value=c.payment_days??'';$('#customer-name').textContent=c.name;$('#customer-dialog').showModal()})}
async function openPreview(id){const invoice=await api(`/api/invoices/${id}`);state.activeInvoice=invoice;$('#preview-content').innerHTML=`<div class="preview-meta"><div><span>Cliente</span><strong>${esc(invoice.customer_name)}</strong><br>${esc(invoice.tax_id)}<br>${esc(invoice.billing_address)}</div><div><span>Número propuesto</span><strong>${esc(invoice.display_invoice_number||'Pendiente de configurar')}</strong><br>Periodo ${date(invoice.period_start)} – ${date(invoice.period_end)}<br>Destinatario ${esc(invoice.recipient_email)}</div></div><div class="table-wrap"><table><thead><tr><th>Línea</th><th>Tarifa</th><th class="numeric">GB incl.</th><th class="numeric">GB cons.</th><th class="numeric">Exceso</th><th class="numeric">Otros</th><th class="numeric">Descuento</th><th class="numeric">Importe</th></tr></thead><tbody>${invoice.lines.map(l=>`<tr><td>${esc(l.line_identifier)}</td><td>${esc(l.rate_name)}</td><td class="numeric">${l.included_gb??'—'}</td><td class="numeric">${l.consumed_gb??'—'}</td><td class="numeric">${l.excess_gb??'0'}</td><td class="numeric">${money(l.other_charges_cents+l.usage_charges_cents)}</td><td class="numeric">${money(l.discount_cents)}</td><td class="numeric"><strong>${money(l.amount_cents)}</strong></td></tr>`).join('')}</tbody></table></div><div class="preview-total"><span>Base ${money(invoice.subtotal_cents)}</span><span>IVA ${money(invoice.vat_cents)}</span><strong>Total ${money(invoice.total_cents)}</strong></div>${!invoice.invoice_number&&invoice.status==='Lista para revisión'?'<button class="text-button" id="discard-preview">Descartar esta vista previa</button>':''}`;$('#confirmation-input').value='';$('#approval-error').hidden=true;$('#preview-dialog').showModal();const discard=$('#discard-preview');if(discard)discard.onclick=async()=>{if(!confirm('¿Descartar esta vista previa para poder corregirla?'))return;await api(`/api/invoices/${invoice.id}/discard`,{method:'POST'});$('#preview-dialog').close();toast('Vista previa descartada');await load()}}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));$$('[data-action="new-invoice"]').forEach(b=>b.onclick=()=>{const select=$('#invoice-form select');select.innerHTML='<option value="">Selecciona un cliente</option>'+state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#invoice-dialog').showModal()});$$('[data-close="preview"]').forEach(b=>b.onclick=()=>$('#preview-dialog').close());
$('#sync-button').onclick=async e=>{e.currentTarget.disabled=true;try{const r=await api('/api/sync/nexlink',{method:'POST'});toast(`Sincronizados ${r.services} servicios y ${r.calls} consumos`);await load()}catch(err){toast(err.message)}finally{e.currentTarget.disabled=false}};
$('#invoice-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),err=$('#invoice-form-error');err.hidden=true;try{const invoice=await api('/api/invoices/preview',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});$('#invoice-dialog').close();await load();openPreview(invoice.id)}catch(ex){err.textContent=ex.message;err.hidden=false}};
$('#approve-button').onclick=async e=>{const err=$('#approval-error');err.hidden=true;e.currentTarget.disabled=true;try{const invoice=await api(`/api/invoices/${state.activeInvoice.id}/approve`,{method:'POST',body:JSON.stringify({confirmation:$('#confirmation-input').value})});toast(`Factura ${invoice.invoice_number} enviada`);$('#preview-dialog').close();await load()}catch(ex){err.textContent=ex.message;err.hidden=false}finally{e.currentTarget.disabled=false}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api('/api/settings',{method:'PATCH',body:JSON.stringify({invoiceSeries:f.invoiceSeries,nextInvoiceNumber:Number(f.nextInvoiceNumber),defaultVatRate:Number(f.defaultVatRate)/100,defaultPaymentDays:Number(f.defaultPaymentDays)})});toast('Configuración guardada');await load()};
$('#new-rate').onclick=()=>$('#rate-dialog').showModal();$('#rate-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api('/api/rates',{method:'POST',body:JSON.stringify({name:f.name,serviceType:f.serviceType,monthlyFeeCents:Math.round(Number(f.monthlyFee)*100),includedGb:f.includedGb?Number(f.includedGb):null,includedMinutes:null,excessGbCents:f.excessGb?Math.round(Number(f.excessGb)*100):null,fixedChargesCents:Math.round(Number(f.fixedCharges||0)*100)})});$('#rate-dialog').close();toast('Tarifa creada');await load()};
$('#usage-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api(`/api/services/${f.serviceId}/data-usage`,{method:'POST',body:JSON.stringify({periodStart:f.periodStart,periodEnd:f.periodEnd,consumedGb:Number(f.consumedGb)})});$('#usage-dialog').close();toast('Consumo verificado guardado')};
$('#customer-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api(`/api/customers/${f.customerId}`,{method:'PATCH',body:JSON.stringify({taxId:f.taxId,billingAddress:f.billingAddress,billingEmail:f.billingEmail,vatRate:f.vatRate?Number(f.vatRate)/100:null,paymentDays:f.paymentDays===''?null:Number(f.paymentDays),invoiceSeries:null})});$('#customer-dialog').close();toast('Datos fiscales guardados');await load()};
load().catch(err=>toast(err.message));
